kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zhongshannanfang
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 100Gi