apiVersion: v1
kind: Service
metadata:
  name: school-nginx
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    name: school-http
  selector:
    k8s-app: school-nginx
  type: LoadBalancer